### ISSUE TITLE
How to prevent RM2 from going asleep during the backup process?

### ISSUE THREAD

**Issue by sergei-mironov** [cherti/remarkable-cli-tooling#5]
Web interface goes down after a while with the  'Press the button to continue' message. The backup process silently stops when it happens. Is it possible to force RM2 stay awake?

**Comment by cherti** [comment]
not as I am aware, you can disable that behavior entirely in the rM's settings, but you cannot externally force it (except maybe fiddling with the settings, restarting xochitl before that, change the settings back afterwards, but this sounds to me just as an invitation for things to break if it works at all). Occasionally opening and closing the menu on the device resets the sleep timer, just a workaround but it does work to keep the device awake.

**Comment by cherti** [comment]
Closing this as I currently see no reasonable way of fixing this on the side of the tooling, unfortunately.
